CREATE DATABASE IF NOT EXISTS TournamentDB;
USE TournamentDB;

CREATE TABLE IF NOT EXISTS Players (
    PlayerID SERIAL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    PhoneNumber VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS Teams (
    TeamID SERIAL PRIMARY KEY,
    TeamName VARCHAR(100) NOT NULL UNIQUE,
    CaptainID INTEGER REFERENCES Players(PlayerID) ON DELETE SET NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TeamMembers (
    TeamID INTEGER REFERENCES Teams(TeamID) ON DELETE CASCADE,
    PlayerID INTEGER REFERENCES Players(PlayerID) ON DELETE CASCADE,
    JoinedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TeamID, PlayerID)
);

CREATE TABLE IF NOT EXISTS Matches (
    MatchID SERIAL PRIMARY KEY,
    Team1ID INTEGER REFERENCES Teams(TeamID) ON DELETE CASCADE,
    Team2ID INTEGER REFERENCES Teams(TeamID) ON DELETE CASCADE,
    MatchDate TIMESTAMP NOT NULL,
    Location VARCHAR(100),
    Status VARCHAR(20) DEFAULT 'Scheduled',
    CHECK (Team1ID <> Team2ID)
);
